### ISSUE TITLE
Cron fails with djano.core.exceptions.ValidationError

### ISSUE THREAD

**Issue by neverpanic** [macports/macports-webapp#124]
```
Cronic detected failure or error output for the command:
/var/www/webapp/cron.sh

RESULT CODE: 1

ERROR OUTPUT:
Traceback (most recent call last):
  File "/code/app/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/code/app/ports/management/commands/fetch-build-history.py", line 11, in handle
    BuildHistory.populate()
  File "/code/app/ports/models/buildhistory.py", line 114, in populate
    load_database(build_data_summary)
  File "/code/app/ports/models/buildhistory.py", line 95, in load_database
    build.save()
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1334, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1278, in as_sql
    for obj in self.query.objs
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1278, in <listcomp>
    for obj in self.query.objs
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1277, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1218, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/fields/__init__.py", line 789, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/fields/__init__.py", line 2218, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/fields/__init__.py", line 2213, in get_prep_value
    return self.to_python(value)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/fields/__init__.py", line 2200, in to_python
    params={'value': value},
django.core.exceptions.ValidationError: ["'1 day, 7:23:56' value has an invalid format. It must be in HH:MM[:ss[.uuuuuu]] format."]

STANDARD OUTPUT:
```

**Comment by arjunsalyan** [comment]
It is probably this build: https://build.macports.org/builders/ports-10.12_x86_64-builder/builds/99639

The elapsed time has crossed 24 hours, which gets converted to "X Days", so we are getting a ValidationError because the `time_elapsed` field was misusing a `TimeField`. I wasn't aware of the available `DurationField` which should be used in this case. I have made the changes, and will create a PR after running some tests.
