### ISSUE TITLE
Webapp Cron failed, please analyze

### ISSUE THREAD

**Issue by neverpanic** [macports/macports-webapp#214]
The cron failed on 2020-05-12 20:50:19 UTC:
```
Cronic detected failure or error output for the command:
/var/www/webapp/cron.sh

RESULT CODE: 1

ERROR OUTPUT:
Traceback (most recent call last):
  File "/code/app/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/code/app/ports/management/commands/update-portinfo.py", line 22, in handle
    data = Port.PortIndexUpdateHandler().sync_and_open_file()
  File "/code/app/ports/models/port.py", line 299, in sync_and_open_file
    data = json.load(file)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

STANDARD OUTPUT:

Willkommen auf dem RSYNC-server auf ftp.fau.de.
Nicht all unsere Mirror sind per rsync verfuegbar.

Welcome to the RSYNC daemon on ftp.fau.de.
Not all of our mirrors are available through rsync.
```

This may be a temporary issue since I've only seen it once, but I'd still like you to take a look.

Feel free to close this, if it's a transient issue and no further action needs to be taken.

**Comment by arjunsalyan** [comment]
I remember merging some changes around the time, also we had builds.macports.org down for some time, which could have resulted in a broken portindex.json.

**Comment by mojca** [comment]
May I suggest adding a simple error handling around this (a simple `try` block)?
If fetching or parsing the file fails (it could simply be that the file was fetched at the time when the file itself was in the middle of the update), this doesn't need to be fatal, it will be updated next time.

**Comment by neverpanic** [comment]
I guess since I haven't seen this again, we can just ignore this for now. If you agree, feel free to close the ticket.

**Comment by mojca** [comment]
Some simple try/catch has been added, so let's close this one for now and reopen if it happens again.
